# Dockerfile.dev
FROM node:22.14.0

WORKDIR /app

# Copiamos solo los archivos necesarios para instalar dependencias
COPY package*.json ./
RUN npm install

# Copiamos el resto del código
COPY . .

EXPOSE 3000

# Usamos el script de desarrollo que tengas en package.json (por ejemplo "dev")
CMD ["npm", "run", "dev"]
